### ISSUE TITLE
Does it support wildcard domains?

### ISSUE THREAD

**Issue by pc-magas** [tg123/chrome-hostadmin#32]
Hello I came across the https://chrome.google.com/webstore/detail/hostadmin-app/mfoaclfeiefiehgaojbmncmefhdnikeg?hl=en-US and I want to know whether the pluving supports wildcard domains as well.

I ask more about the capabilities of the plugin rather than a bug issue.

Your sincerelly,
Dimitrios

**Comment by tg123** [comment]
unfortunately,  * is not support by hostfile :(
