### ISSUE TITLE
Will this be migrated to a Progressive Web App?

### ISSUE THREAD

**Issue by GalacticHero228** [tg123/chrome-hostadmin#33]
Google doesn't allow downloads of the app anymore and asks me to remove it every time I launch it.
This is due to them sunsetting old apps. Likely ones on WebManifestV2 as they are moving to V3 and will only support Progressive Web Apps. 

It looks like this project hasn't been updated in a while, but is this planned for an update? 

Reference: https://support.google.com/chrome/thread/174381169?visit_id=638012622324473738-4154304828&p=chrome_app_deprecation&rd=1

**Comment by tg123** [comment]
due to write api to /etc/hosts is banned

**Comment by GalacticHero228** [comment]
That is sad. This app really helped me flip around my 4 hosts. Thanks for the answer!
